name: Outdated Version Action

on: push

jobs:
  outdated-version:
    runs-on: ubuntu-latest
    steps:
      - name: outdated version
        uses: ycjcl868@outdated-version-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
